## ***getting start with numpy***

In [1]:
import numpy as np

In [2]:
#creating array
arr=np.array([1,2,3,4,5])
arr2=np.array([[1,2],[3,4],[5,6]])

In [3]:
arr


array([1, 2, 3, 4, 5])

In [4]:
print(np.__version__)

1.26.4


In [5]:
# o d array
mat=np.array(12)
print(mat)

#1D
print(arr)

# 2D
print(arr2)

# 3D
arr3=np.array([[[1,2],[3,5]],[[6,7],[8,9]]])
print(arr3)

12
[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
[[[1 2]
  [3 5]]

 [[6 7]
  [8 9]]]


In [154]:
lst1=[1,2,3,4,5]
lst2=[6,7,8,9,10]
lst3=[11,12,13,14,15]
arr4=np.array([lst1,lst2,lst3])
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [156]:
print(arr4.shape)

(3, 5)


***play with dimension***

In [151]:
type(arr)

numpy.ndarray

In [6]:
# check the dimension
print(arr.ndim)
create_arr=np.array([1,2,3,4],ndmin=5)
print(create_arr)
print(create_arr.ndim)

1
[[[[[1 2 3 4]]]]]
5


In [7]:
# indexing
print(arr[0])
print(arr2[0,1])
print(arr[0:2])
print(arr[3]+arr3[1,0,1])
print(arr2[1,0:])
print(arr3[1,0:1,1]) # how?

1
2
[1 2]
11
[3 4]
[7]


In [8]:
import random
demo=np.random.randint(0,10,(5,7))
print(demo)

[[8 3 1 2 7 9 0]
 [3 9 5 1 4 4 7]
 [9 9 2 5 7 9 9]
 [7 2 3 7 1 0 7]
 [3 2 5 6 9 1 1]]


In [9]:
print(demo[1,2:])
print(demo[2:4,2:4])

[5 1 4 4 7]
[[2 5]
 [3 7]]


### ***data type in numpy is more than that of in python***

*   i - integer
*   b - boolean
*   u - unsigned integer
*   f - float
*   c - complex float
*   m - timedelta
*   M - datetime
*   O - object
*   S - string
*   U - unicode string
*   V - fixed chunk of memory for other type ( void )






In [10]:
print(arr.dtype)

int64


In [11]:
demo2=np.array(demo,dtype='S')
print(demo2)
arr_half=np.array([1.2,3.4,5.6],dtype='i4')
print(arr_half.dtype)

[[b'8' b'3' b'1' b'2' b'7' b'9' b'0']
 [b'3' b'9' b'5' b'1' b'4' b'4' b'7']
 [b'9' b'9' b'2' b'5' b'7' b'9' b'9']
 [b'7' b'2' b'3' b'7' b'1' b'0' b'7']
 [b'3' b'2' b'5' b'6' b'9' b'1' b'1']]
int32


In [12]:
mat2 = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [14]:
demo3=demo.astype('f')
demo4=demo.astype(bool)
print(demo3)
print(demo4)

[[8. 3. 1. 2. 7. 9. 0.]
 [3. 9. 5. 1. 4. 4. 7.]
 [9. 9. 2. 5. 7. 9. 9.]
 [7. 2. 3. 7. 1. 0. 7.]
 [3. 2. 5. 6. 9. 1. 1.]]
[[ True  True  True  True  True  True False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True False  True]
 [ True  True  True  True  True  True  True]]


In [15]:
#copy vs view
arr_original=np.array([1,2,34,56])
arr_copy=arr_original.copy()
arr_view=arr_original.view()
# The view SHOULD be affected by the changes made to the original array.
arr_original[1]=20
print(arr_copy)
print(arr_view)

[ 1  2 34 56]
[ 1 20 34 56]


### check if array owns the data

In [16]:
print(arr_original.base)
print(arr_copy.base)
print(arr_view.base)

None
None
[ 1 20 34 56]


### **array attributes**

In [17]:
# shape-tupe of row and column
print(demo.shape)
print(mat.shape)
print(arr.shape)
print(arr2.shape)
print(arr3.shape)

(5, 7)
()
(5,)
(3, 2)
(2, 2, 2)


In [18]:
# reshaping
demo5=np.random.randint(0,100,(10));
print(demo5)

[92 78 88 48 10 38 74 66 61 72]


In [19]:
dem6=demo5.reshape(2,4)
print(dem6)

ValueError: cannot reshape array of size 10 into shape (2,4)

In [55]:
demo6=demo5.reshape(2,5)
demo6

array([[10, 38, 61, 48, 72],
       [66, 92, 78, 74, 88]])

In [56]:
print(demo6.base)

[10 38 61 48 72 66 92 78 74 88]


In [57]:
demo5[1]=66
print(demo5)
print(demo6)

[10 66 61 48 72 66 92 78 74 88]
[[10 66 61 48 72]
 [66 92 78 74 88]]


In [58]:
# if you cant speficy a particular dimension to staisfy the size
print(demo6.reshape(-1)) # fattening the array
print(demo5.reshape(2,-1,5))

[10 66 61 48 72 66 92 78 74 88]
[[[10 66 61 48 72]]

 [[66 92 78 74 88]]]


In [158]:
ar=np.arange(1,100,2)
print(ar)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


### **iteration**

In [59]:
#iteration
for i in demo:
  print(i)

[8 3 1 2 7 9 0]
[3 9 5 1 4 4 7]
[9 9 2 5 7 9 9]
[7 2 3 7 1 0 7]
[3 2 5 6 9 1 1]


In [60]:
for j in demo:
  for i in j:
    print(i)

8
3
1
2
7
9
0
3
9
5
1
4
4
7
9
9
2
5
7
9
9
7
2
3
7
1
0
7
3
2
5
6
9
1
1


In [61]:
for i in demo5:
  print(i)

10
66
61
48
72
66
92
78
74
88


In [62]:
# for 3D
# for i in demo:
#   for j in i:
#     for k in j:
#       print(k)
# *****method 2******
for i in np.nditer(arr3):
  print(i)

1
2
3
5
6
7
8
9


In [63]:
#iterate with different datatype
for i in np.nditer(demo5,flags=['buffered'],op_dtypes=['S']):
  print(i)

b'10'
b'66'
b'61'
b'48'
b'72'
b'66'
b'92'
b'78'
b'74'
b'88'


In [64]:
#iterate with step space
for i in np.nditer(demo5[::2]):
  print(i)

10
61
72
92
74


In [65]:
for i in np.nditer(demo6[:, ::2]):
  print(i)

10
61
72
66
78
88


In [66]:
# index with element
for id,i in np.ndenumerate(demo5):
  print(id,i)

(0,) 10
(1,) 66
(2,) 61
(3,) 48
(4,) 72
(5,) 66
(6,) 92
(7,) 78
(8,) 74
(9,) 88


In [67]:
for id ,i in np.ndenumerate(demo6):
  print(id,i)

(0, 0) 10
(0, 1) 66
(0, 2) 61
(0, 3) 48
(0, 4) 72
(1, 0) 66
(1, 1) 92
(1, 2) 78
(1, 3) 74
(1, 4) 88


###**joining**

In [68]:
print(np.concatenate((arr,demo5)))

[ 1. -2.  3.  2. -9.  8. 10. 66. 61. 48. 72. 66. 92. 78. 74. 88.]


In [69]:
#joining along row
print(np.concatenate((demo,demo3),axis=0))
print("row")
print(np.concatenate((demo,demo3),axis=1))

[[8. 3. 1. 2. 7. 9. 0.]
 [3. 9. 5. 1. 4. 4. 7.]
 [9. 9. 2. 5. 7. 9. 9.]
 [7. 2. 3. 7. 1. 0. 7.]
 [3. 2. 5. 6. 9. 1. 1.]
 [8. 3. 1. 2. 7. 9. 0.]
 [3. 9. 5. 1. 4. 4. 7.]
 [9. 9. 2. 5. 7. 9. 9.]
 [7. 2. 3. 7. 1. 0. 7.]
 [3. 2. 5. 6. 9. 1. 1.]]
row
[[8. 3. 1. 2. 7. 9. 0. 8. 3. 1. 2. 7. 9. 0.]
 [3. 9. 5. 1. 4. 4. 7. 3. 9. 5. 1. 4. 4. 7.]
 [9. 9. 2. 5. 7. 9. 9. 9. 9. 2. 5. 7. 9. 9.]
 [7. 2. 3. 7. 1. 0. 7. 7. 2. 3. 7. 1. 0. 7.]
 [3. 2. 5. 6. 9. 1. 1. 3. 2. 5. 6. 9. 1. 1.]]


In [70]:
# join array using stack function 2D to 3D and 1D to 2D
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
print(np.stack((arr_copy,arr_original),axis=1))
print(np.stack((demo,demo3),axis=1))

[[ 1  1]
 [ 2 20]
 [34 34]
 [56 56]]
[[[8. 3. 1. 2. 7. 9. 0.]
  [8. 3. 1. 2. 7. 9. 0.]]

 [[3. 9. 5. 1. 4. 4. 7.]
  [3. 9. 5. 1. 4. 4. 7.]]

 [[9. 9. 2. 5. 7. 9. 9.]
  [9. 9. 2. 5. 7. 9. 9.]]

 [[7. 2. 3. 7. 1. 0. 7.]
  [7. 2. 3. 7. 1. 0. 7.]]

 [[3. 2. 5. 6. 9. 1. 1.]
  [3. 2. 5. 6. 9. 1. 1.]]]


In [71]:
# stacking along same axis
print(np.hstack((arr_copy,arr_original)))

[ 1  2 34 56  1 20 34 56]


In [72]:
# stacking along depth
print(np.dstack((arr_copy,arr_original)))

[[[ 1  1]
  [ 2 20]
  [34 34]
  [56 56]]]


In [73]:
# stacking along columns
print(np.vstack((arr_copy,arr_original)))

[[ 1  2 34 56]
 [ 1 20 34 56]]


### **splitting**

In [74]:
print(np.array_split(arr,3))
print(demo,"\n")
new_arr=np.array_split(demo,3)
for i in new_arr:
  print(i)
  print("\n")

[array([ 1., -2.]), array([3., 2.]), array([-9.,  8.])]
[[8 3 1 2 7 9 0]
 [3 9 5 1 4 4 7]
 [9 9 2 5 7 9 9]
 [7 2 3 7 1 0 7]
 [3 2 5 6 9 1 1]] 

[[8 3 1 2 7 9 0]
 [3 9 5 1 4 4 7]]


[[9 9 2 5 7 9 9]
 [7 2 3 7 1 0 7]]


[[3 2 5 6 9 1 1]]




In [75]:
#slicing along columns
new_arr2=np.array_split(demo,3,axis=1)
for i in new_arr2:
  print(i,"\n")

[[8 3 1]
 [3 9 5]
 [9 9 2]
 [7 2 3]
 [3 2 5]] 

[[2 7]
 [1 4]
 [5 7]
 [7 1]
 [6 9]] 

[[9 0]
 [4 7]
 [9 9]
 [0 7]
 [1 1]] 



In [76]:
print(np.split(demo,5))
print(np.split(demo,7))

[array([[8, 3, 1, 2, 7, 9, 0]]), array([[3, 9, 5, 1, 4, 4, 7]]), array([[9, 9, 2, 5, 7, 9, 9]]), array([[7, 2, 3, 7, 1, 0, 7]]), array([[3, 2, 5, 6, 9, 1, 1]])]


ValueError: array split does not result in an equal division

In [77]:
print(np.hsplit(demo,7))

[array([[8],
       [3],
       [9],
       [7],
       [3]]), array([[3],
       [9],
       [9],
       [2],
       [2]]), array([[1],
       [5],
       [2],
       [3],
       [5]]), array([[2],
       [1],
       [5],
       [7],
       [6]]), array([[7],
       [4],
       [7],
       [1],
       [9]]), array([[9],
       [4],
       [9],
       [0],
       [1]]), array([[0],
       [7],
       [9],
       [7],
       [1]])]


In [78]:
print(np.vsplit(demo,5))
# print(np.dsplit(demo,5))


[array([[8, 3, 1, 2, 7, 9, 0]]), array([[3, 9, 5, 1, 4, 4, 7]]), array([[9, 9, 2, 5, 7, 9, 9]]), array([[7, 2, 3, 7, 1, 0, 7]]), array([[3, 2, 5, 6, 9, 1, 1]])]


###**searching and sorting**

In [79]:
demo7=np.array([1,2,3,4,5,4,4,6,7,4])
x=np.where(demo7==4)
print(x)

(array([3, 5, 6, 9]),)


In [80]:
print(demo,'\n')
y=np.where(demo==9)
print(y)
for i in range(0,len(y[0])):
  print(demo[y[0][i]][y[1][i]])

[[8 3 1 2 7 9 0]
 [3 9 5 1 4 4 7]
 [9 9 2 5 7 9 9]
 [7 2 3 7 1 0 7]
 [3 2 5 6 9 1 1]] 

(array([0, 1, 2, 2, 2, 2, 4]), array([5, 1, 0, 1, 5, 6, 4]))
9
9
9
9
9
9
9


In [81]:
#even elements in demo
z=np.where(demo%2==0)
print(z)

(array([0, 0, 0, 1, 1, 2, 3, 3, 4, 4]), array([0, 3, 6, 4, 5, 2, 1, 5, 1, 3]))


In [82]:
for i in range(0,len(z[0])):
  print(demo[z[0][i]][z[1][i]])

8
2
0
4
4
2
2
0
2
6


In [83]:
#assuming the search/find place for insertion to be done on the sorted array
# x=np.searchsorted(arr,val_to_be_found)
arr_sorted=np.array([1,2,4,5,6,7])
val=np.searchsorted(arr_sorted,2)
print(val)

1


In [84]:
# the above method search/ find place to insert from left to right
# in order to right to left
val2=np.searchsorted(arr_sorted,2,side='right')
print(val2)

2


In [85]:
# multiple values
arr13 = np.array([1, 3, 5, 7])
val3 = np.searchsorted(arr13, [2, 4,1, 6])
print(val3)

[1 2 0 3]


In [86]:
demo5

array([10, 66, 61, 48, 72, 66, 92, 78, 74, 88])

In [87]:
print(np.sort(demo5))

[10 48 61 66 66 72 74 78 88 92]


In [88]:
print(np.sort(demo)) # or axis=1 all same

[[0 1 2 3 7 8 9]
 [1 3 4 4 5 7 9]
 [2 5 7 9 9 9 9]
 [0 1 2 3 7 7 7]
 [1 1 2 3 5 6 9]]


In [89]:
print(np.sort(demo,axis=0))

[[3 2 1 1 1 0 0]
 [3 2 2 2 4 1 1]
 [7 3 3 5 7 4 7]
 [8 9 5 6 7 9 7]
 [9 9 5 7 9 9 9]]


In [90]:
print(demo4,'\n')
print(np.sort(demo4,axis=0),'\n')
print(np.sort(demo4,axis=1),"\n")
print(np.sort(demo4),'\n')

[[ True  True  True  True  True  True False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True False  True]
 [ True  True  True  True  True  True  True]] 

[[ True  True  True  True  True False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]] 

[[False  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [False  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]] 

[[False  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [False  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]] 



Filtering Arrays


---


Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.



In [91]:
demo5

array([10, 66, 61, 48, 72, 66, 92, 78, 74, 88])

In [92]:
# mapping demo5 with the boolean the false wale nhi print hongey
boolean=[True,True,True,False,True,True,True,False,True,True]
newarr=demo5[boolean]
print(newarr)

[10 66 61 72 66 92 74 88]


In [93]:
#In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.
filter_arr=[]
for i in demo5:
  if i>50:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr2=demo5[filter_arr]
print(demo5)
print(filter_arr)
print(newarr2)

[10 66 61 48 72 66 92 78 74 88]
[False, True, True, False, True, True, True, True, True, True]
[66 61 72 66 92 78 74 88]


In [94]:
# creating filter directly from the array
filter_arr2=demo5>50
print(filter_arr2)
newarr3=demo5[filter_arr2]
print(newarr3)

[False  True  True False  True  True  True  True  True  True]
[66 61 72 66 92 78 74 88]




---



##***Random Number Play***

In [95]:
from numpy import random
# random integer
xu = random.randint(100)

print(xu)

92


In [96]:
# float number between 0 and 1
fu=random.rand()
print(fu)

0.05592935107587094


In [97]:
array = random.randint(100,size=(5,2))
print(array)

[[76 90]
 [41 77]
 [41 94]
 [51 60]
 [35  5]]


In [98]:
array2=np.arange(10)
print(array2)

[0 1 2 3 4 5 6 7 8 9]


In [99]:
array3=np.random.randint(0,50,(5,4))
print(array3)

[[11 35 48  4]
 [34 41 18  8]
 [15 34 30 13]
 [ 8 43 27 19]
 [24 17 44 39]]


In [100]:
array4=np.random.rand(3,5)
print(array4)

[[0.12918965 0.20781896 0.74868354 0.99290795 0.54572374]
 [0.84911161 0.30551531 0.2745428  0.8603813  0.79182614]
 [0.84766351 0.38817252 0.69231977 0.79314558 0.50755418]]


In [101]:
#generating rondom from a list
array5=np.random.choice([2,4,6,8],(4,5))
print(array5)

[[4 8 6 8 4]
 [8 8 8 2 6]
 [8 2 6 6 4]
 [4 2 8 2 4]]


**What is Data Distribution?**

Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

The random module offer methods that returns randomly generated data distributions.

**Random Distribution**

A random distribution is a set of random numbers that follow a certain probability density function.

**Probability Density Function**: A function that describes a continuous probability. i.e. probability of all values in an array.

---



**example 1:**Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0

**Note; sum of all probabilities should be 1 always**

In [102]:
prob=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0],size=(100))
print(prob)

[5 7 7 7 7 7 3 3 5 7 7 7 3 5 7 7 7 3 7 7 7 7 7 7 5 5 3 7 5 7 7 5 7 5 3 3 7
 7 3 5 5 7 7 7 7 7 5 3 7 7 3 7 7 7 5 7 3 7 7 5 3 7 7 5 5 7 7 7 7 7 3 7 7 3
 7 7 3 7 5 7 7 5 5 7 5 5 5 7 7 5 7 5 7 7 5 5 7 5 5 7]


In [103]:
#shuffling the array
# method 1
print(demo5)
random.shuffle(demo5)
print(demo5)

[10 66 61 48 72 66 92 78 74 88]
[92 78 61 72 48 66 66 10 74 88]


In [104]:
#shuffle method make changes in original array
# method2
print(demo5)
shuffle_arr=random.permutation(demo5)
print(demo5)
print(shuffle_arr)

[92 78 61 72 48 66 66 10 74 88]
[92 78 61 72 48 66 66 10 74 88]
[74 48 72 66 10 92 78 61 88 66]


rest random will be done after matplotlib and seaborn

###***NUMPY UFUNC***

In [105]:
# ADDITION
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)


[5, 7, 9, 11]


In [106]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [107]:
#SUBTRACTION
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [108]:
#MULTIPLICATION
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [109]:
#DIVISION
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [110]:
# ARRAY 1 RAISE TO THE POWER ARRAY 2
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [111]:
# REMAINDER
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)
newarr2=np.remainder(arr1,arr2)
print(newarr)
print(newarr2)

[ 1  6  3  0  0 27]
[ 1  6  3  0  0 27]


In [112]:
# QUOTIENT AND REMAINDER
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [113]:
# ABSOLUTE VALUE
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


###rounding off

In [114]:
arr_float=np.array([0.1234,-2.90,2.15,1.567,-9.46,7.346])
arr1=np.trunc(arr_float)
print(arr1)

[ 0. -2.  2.  1. -9.  7.]


In [115]:
arr2=np.fix(arr_float)
print(arr2)

[ 0. -2.  2.  1. -9.  7.]


In [116]:
aar=np.around(arr_float)
print(aar)

[ 0. -3.  2.  2. -9.  7.]


In [117]:
aarr=np.floor(arr_float)
print(aarr)

[  0.  -3.   2.   1. -10.   7.]


In [118]:
arr=np.ceil(arr_float)
print(arr)

[ 1. -2.  3.  2. -9.  8.]


Lograthmic

In [119]:
print(demo5)

[92 78 61 72 48 66 66 10 74 88]


In [120]:
print(np.log2(demo5))

[6.52356196 6.28540222 5.93073734 6.169925   5.5849625  6.04439412
 6.04439412 3.32192809 6.20945337 6.45943162]


In [121]:
print(np.log10(demo5))

[1.96378783 1.8920946  1.78532984 1.8573325  1.68124124 1.81954394
 1.81954394 1.         1.86923172 1.94448267]


In [122]:
print(np.log(demo5))

[4.52178858 4.35670883 4.11087386 4.27666612 3.87120101 4.18965474
 4.18965474 2.30258509 4.30406509 4.47733681]


**Log at Any Base**

NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:

In [123]:
from math import log
nplog=np.frompyfunc(log,2,1)
print(nplog(100,15))

1.7005483074552052


**Summations**

What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.

In [124]:
print(demo5)
print(demo7)

[92 78 61 72 48 66 66 10 74 88]
[1 2 3 4 5 4 4 6 7 4]


In [125]:
newarr=np.sum([demo5])
newarr2=np.sum([demo7])
print(newarr)
print(newarr2)

655
40


In [126]:
newarr=np.sum([demo5,demo7])
print(newarr)

695


In [127]:
demo6

array([[92, 78, 61, 72, 48],
       [66, 66, 10, 74, 88]])

In [128]:
#SUMMATION OVER A AXIS
newarr=np.sum([demo6],axis=1)
newarr2=np.sum(demo6,axis=1)
print(newarr)
print(newarr2)

[[158 144  71 146 136]]
[351 304]


In [129]:
#cummulative sum
#sum of that element and all the elements before that
print(demo7)
newarr=np.cumsum((demo7))
print(newarr)

[1 2 3 4 5 4 4 6 7 4]
[ 1  3  6 10 15 19 23 29 36 40]


In [130]:
#product of all elements
print(np.prod(demo7))

322560


In [131]:
print(np.prod([demo6],axis=1))
print(np.prod(demo6,axis=1))

[[6072 5148  610 5328 4224]]
[1512815616  283662720]


In [132]:
#cummulative product
print(np.cumprod(demo7))

[     1      2      6     24    120    480   1920  11520  80640 322560]


**Differences**

A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

In [133]:
print(np.diff(demo7))

[ 1  1  1  1 -1  0  2  1 -3]


In [134]:
#calculating lcm
print(np.lcm(demo7,demo5))

[ 92  78 183  72 240 132 132  30 518  88]


In [135]:
print(np.lcm.reduce(demo7))

420


In [136]:
#calculating gcd
print(np.gcd.reduce(demo7))
print(np.gcd(demo5,demo7))

1
[1 2 1 4 1 2 2 2 1 4]


Trigonometry

In [137]:
print(np.sin(np.pi/2))

1.0


In [138]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [139]:
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)


[1.57079633 3.14159265 4.71238898 6.28318531]


**Finding Angles**

Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [140]:
x = np.arcsin(1.0)
print(x)

1.5707963267948966


In [141]:
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


**Hypotenues**

Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [142]:
base = 3
perp = 4

x = np.hypot(base, perp)
print(x)

5.0


**Hyperbolic Functions**

NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values..

In [143]:
x = np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [144]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)
print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


**Finding Angles**

Finding angles from values of hyperbolic sine, cos, tan. E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.

In [145]:
arr = np.array([0.1, 0.2, 0.5])
x = np.arctanh(arr)
print(x)

[0.10033535 0.20273255 0.54930614]


**Create Sets in NumPy**

We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

In [146]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


**Finding Union**

To find the unique values of two arrays, use the union1d() method.

In [147]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


**Finding Intersection**

To find only the values that are present in both arrays, use the intersect1d() method.

In [148]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


**Finding Difference**

To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.



In [149]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


**Finding Symmetric Difference**

To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

In [150]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]


###Mathematical operations

In [165]:
np_array=np.arange(1,20,3)
print(np_array)
arr_made=np_array+2

[ 1  4  7 10 13 16 19]


In [166]:
np_array+arr_made


array([ 4, 10, 16, 22, 28, 34, 40])

In [167]:
arr_made-np_array

array([2, 2, 2, 2, 2, 2, 2])

In [168]:
arr_made*np_array

array([  3,  24,  63, 120, 195, 288, 399])

In [170]:
demo

array([[8, 3, 1, 2, 7, 9, 0],
       [3, 9, 5, 1, 4, 4, 7],
       [9, 9, 2, 5, 7, 9, 9],
       [7, 2, 3, 7, 1, 0, 7],
       [3, 2, 5, 6, 9, 1, 1]])

In [172]:
demo3

array([[8., 3., 1., 2., 7., 9., 0.],
       [3., 9., 5., 1., 4., 4., 7.],
       [9., 9., 2., 5., 7., 9., 9.],
       [7., 2., 3., 7., 1., 0., 7.],
       [3., 2., 5., 6., 9., 1., 1.]], dtype=float32)

In [173]:
demo*demo3

array([[64.,  9.,  1.,  4., 49., 81.,  0.],
       [ 9., 81., 25.,  1., 16., 16., 49.],
       [81., 81.,  4., 25., 49., 81., 81.],
       [49.,  4.,  9., 49.,  1.,  0., 49.],
       [ 9.,  4., 25., 36., 81.,  1.,  1.]])

In [178]:
matrix=np.multiply(demo,demo3)
print(matrix)

[[64.  9.  1.  4. 49. 81.  0.]
 [ 9. 81. 25.  1. 16. 16. 49.]
 [81. 81.  4. 25. 49. 81. 81.]
 [49.  4.  9. 49.  1.  0. 49.]
 [ 9.  4. 25. 36. 81.  1.  1.]]


In [186]:
matrix2=np.dot(demo,demo3.T)
matrix2
# in order to make row of demo=col of demo3 we use transpose by T

array([[208., 122., 241.,  86., 119.],
       [122., 197., 250., 114., 105.],
       [241., 250., 402., 192., 166.],
       [ 86., 114., 192., 161.,  98.],
       [119., 105., 166.,  98., 157.]])

In [184]:
demo.dot(demo3.T)

array([[208., 122., 241.,  86., 119.],
       [122., 197., 250., 114., 105.],
       [241., 250., 402., 192., 166.],
       [ 86., 114., 192., 161.,  98.],
       [119., 105., 166.,  98., 157.]])

Indexing

In [187]:
print(demo[1:2])

[[3 9 5 1 4 4 7]]


In [188]:
print(demo[1:1,1:1])

[]


In [189]:
print(demo[1:2,1:2])

[[9]]


In [195]:
a=np.array([[1,4,7,10],[2,5,8,11],[3,6,9,12]])
print(a[0:2,1:3])
print(a[1:,0:2])
print(a[1:,2:])

[[4 7]
 [5 8]]
[[2 5]
 [3 6]]
[[ 8 11]
 [ 9 12]]
